# Generated by Django 4.0.4 on 2022-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='participant',
            field=models.ManyToManyField(blank=True, to='meetups.participant'),
        ),
    ]
