# Generated by Django 4.0.4 on 2022-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
